name: DirectorOfChaos
version: 1.0
main: main.java
description: tries to put Chaos in your world.
load: startup
commands:
    event:
        usage: /<command>
        description: Chaos. Chaos everywhere.
permissions:
    Events.Use:
        description: Use all event commands
        default: op
        children:
            Events.TP: true
    Events.TP:
        description: Use the event tp command
        default: op